insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Drucie Goodbourn',  'Exploit real-time e-commerce',             '$203.23',  '$43.37',  0, false, true,  true,  false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Marcia Aggiss',     'Utilize real-time interfaces',             '$260.31',  '$35.96', 40, true,  true,  true,  false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Giovanni Bigg',     'Extend strategic e-services',              '$272.00', '$151.04', 30, false, true,  false, false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Duffie Eynon',      'Iterate integrated solutions',             '$271.58', '$141.40', 40, false, false, true,  true);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Anselma McKennan',  'Cultivate magnetic e-commerce',            '$278.43',  '$54.44',  0, true,  true,  false, true);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Gert Kira',         'Architect vertical ROI',                   '$282.54', '$102.61',  0, false, true,  true,  false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Clerc Djakovic',    'Disintermediate extensible architectures', '$295.38', '$181.27', 10, false, true,  true,  false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Stacee Elsy',       'Extend leading-edge methodologies',        '$283.08',  '$97.96',  0, false, true,  false, false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Dorotea Bonhill',   'Integrate one-to-one systems',             '$258.51',  '$52.25',  0, true,  false, true,  true);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Minni Bunney',      'Revolutionize 24/7 infrastructures',       '$260.79',  '$33.69',  0, false, true,  false, true);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Berty Gandley',     'Enhance innovative e-services',            '$256.54', '$160.98', 20, false, false, true,  false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Raynard Tesdale',   'Maximize 24/365 e-tailers',                '$262.07',  '$34.06', 20, false, true,  true,  false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Joanna Hutfield',   'Scale integrated architectures',           '$257.66',  '$32.97',  0, true,  true,  false, true);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Dannie Glidder',    'E-enable frictionless web services',       '$288.19',  '$90.52', 50, false, true,  true,  true);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Timmie Adshede',    'Strategize B2B channels',                  '$232.27',  '$44.83', 40, false, true,  true,  false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Fernando Neads',    'Syndicate compelling deliverables',        '$287.45', '$101.89',  0, false, true,  false, true);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Teddy Guilliland',  'Utilize bleeding-edge users',              '$281.37', '$146.21',  0, false, false, true,  true);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Paloma Grebert',    'Cultivate 24/365 networks',                '$270.99', '$184.76', 30, false, false, true,  false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Kristos Usher',     'Embrace plug-and-play platforms',          '$278.36',  '$77.71', 30, true,  true,  false, true);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Darcey Rohmer',     'Target innovative paradigms',              '$298.94', '$130.01', 30, false, true,  true,  false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Cristie Isacsson',  'Generate open-source e-business',          '$276.57', '$113.25',  0, false, true,  true,  false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Lindsay Coutthart', 'Implement user-centric e-markets',         '$254.70', '$115.31', 50, false, true,  false, true);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Helyn Schneidar',   'Utilize magnetic supply-chains',           '$279.70',  '$77.86', 20, true,  true,  true,  false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Bette-ann Askem',   'E-enable dot-com supply-chains',           '$297.83', '$110.15', 20, false, false, true,  false);
insert into books (author, title, priceOld, price, discount, bestseller, recomended, news, popular) values ('Dom Robuchon',      'Facilitate efficient eyeballs',            '$232.30', '$131.48',  0, false, true,  false, true);

insert into genres (id, genre, parent_id, level) values (1,  'Лёгкое чтение',                               0, 1);
insert into genres (id, genre, parent_id, level) values (2,  'Фантастика',                                  1, 2);
insert into genres (id, genre, parent_id, level) values (3,  'Боевики',                                     1, 2);
insert into genres (id, genre, parent_id, level) values (4,  'Детективы',                                   1, 2);
insert into genres (id, genre, parent_id, level) values (5,  'Триллер',                                     4, 3);
insert into genres (id, genre, parent_id, level) values (6,  'Крутой детектив',                             4, 3);
insert into genres (id, genre, parent_id, level) values (7,  'Иронический детектив',                        4, 3);
insert into genres (id, genre, parent_id, level) values (8,  'Про маньяков',                                4, 3);
insert into genres (id, genre, parent_id, level) values (9,  'Шпионский детектив',                          4, 3);
insert into genres (id, genre, parent_id, level) values (10, 'Криминальный детектив',                       4, 3);
insert into genres (id, genre, parent_id, level) values (11, 'Классический детектив',                       4, 3);
insert into genres (id, genre, parent_id, level) values (12, 'Политический детектив',                       4, 3);
insert into genres (id, genre, parent_id, level) values (13, 'Фэнтези',                                     1, 2);
insert into genres (id, genre, parent_id, level) values (14, 'Романы',                                      1, 2);
insert into genres (id, genre, parent_id, level) values (15, 'Ужасы',                                       1, 2);
insert into genres (id, genre, parent_id, level) values (16, 'Приключения',                                 1, 2);
insert into genres (id, genre, parent_id, level) values (17, 'Серьёзное чтение',                            0, 1);
insert into genres (id, genre, parent_id, level) values (18, 'Биографии',                                  17, 2);
insert into genres (id, genre, parent_id, level) values (19, 'Деловая литература',                          0, 1);
insert into genres (id, genre, parent_id, level) values (20, 'Управление экономикой',                      19, 2);
insert into genres (id, genre, parent_id, level) values (21, 'Карьера',                                    19, 2);
insert into genres (id, genre, parent_id, level) values (22, 'Маркетинг, PR, реклама',                     19, 2);
insert into genres (id, genre, parent_id, level) values (23, 'Финансы',                                    19, 2);
insert into genres (id, genre, parent_id, level) values (24, 'Бизнес-справочники',                         19, 2);
insert into genres (id, genre, parent_id, level) values (25, 'Личные финансы',                             19, 2);
insert into genres (id, genre, parent_id, level) values (26, 'Менеджмент',                                 19, 2);
insert into genres (id, genre, parent_id, level) values (27, 'Зарубежная деловая литература',              19, 2);
insert into genres (id, genre, parent_id, level) values (28, 'Личная эффективность',                       19, 2);
insert into genres (id, genre, parent_id, level) values (29, 'Тайм-менеджмент',                            19, 2);
insert into genres (id, genre, parent_id, level) values (30, 'Малый бизнес',                               19, 2);
insert into genres (id, genre, parent_id, level) values (31, 'Продажи',                                    19, 2);
insert into genres (id, genre, parent_id, level) values (32, 'Стартапы и создание бизнеса',                19, 2);
insert into genres (id, genre, parent_id, level) values (33, 'Корпоративная культура',                     19, 2);
insert into genres (id, genre, parent_id, level) values (34, 'Банковское дело',                            19, 2);
insert into genres (id, genre, parent_id, level) values (35, 'Логистика',                                  19, 2);
insert into genres (id, genre, parent_id, level) values (36, 'Недвижимость',                               19, 2);
insert into genres (id, genre, parent_id, level) values (37, 'Интернет-бизнес',                            19, 2);
insert into genres (id, genre, parent_id, level) values (38, 'Ораторское искусство / риторика',            19, 2);
insert into genres (id, genre, parent_id, level) values (39, 'Привлечение клиентов и лояльность',          19, 2);
insert into genres (id, genre, parent_id, level) values (40, 'Делопроизводство',                           19, 2);
insert into genres (id, genre, parent_id, level) values (41, 'Переговоры',                                 19, 2);
insert into genres (id, genre, parent_id, level) values (42, 'Государственное и муниципальное управление', 19, 2);
insert into genres (id, genre, parent_id, level) values (43, 'О бизнесе популярно',                        19, 2);
insert into genres (id, genre, parent_id, level) values (44, 'Ценные бумаги / инвестиции',                 19, 2);
insert into genres (id, genre, parent_id, level) values (45, 'Бухучет / налогообложение / аудит',          19, 2);
insert into genres (id, genre, parent_id, level) values (46, 'Бухгалтерский учет в коммерческих банках',   45, 3);
insert into genres (id, genre, parent_id, level) values (47, 'Бухгалтерский учет на предприятиях',         45, 3);
insert into genres (id, genre, parent_id, level) values (48, 'Налоги',                                     45, 3);
insert into genres (id, genre, parent_id, level) values (49, 'Аудит',                                      45, 3);
insert into genres (id, genre, parent_id, level) values (50, 'Российская практика',                        19, 2);
insert into genres (id, genre, parent_id, level) values (51, 'Истории успеха',                             19, 2);
insert into genres (id, genre, parent_id, level) values (52, 'Интернет-маркетинг',                         19, 2);
insert into genres (id, genre, parent_id, level) values (53, 'Лидерство',                                  19, 2);
insert into genres (id, genre, parent_id, level) values (54, 'Управление бизнесом',                        19, 2);
insert into genres (id, genre, parent_id, level) values (55, 'Драматургия',                                 0, 1);
insert into genres (id, genre, parent_id, level) values (56, 'Античная драма',                             55, 2);
insert into genres (id, genre, parent_id, level) values (57, 'Комедия',                                    55, 2);
insert into genres (id, genre, parent_id, level) values (58, 'Российские коммедии',                        57, 3);
insert into genres (id, genre, parent_id, level) values (59, 'Иностранные коммедии',                       57, 3);
insert into genres (id, genre, parent_id, level) values (60, 'Сценарий',                                   55, 2);
insert into genres (id, genre, parent_id, level) values (61, 'Драма, пьеса',                               55, 2);

insert into authors (author) values ('Абгарян Наринэ');
insert into authors (author) values ('Абдуллаев Чингиз');
insert into authors (author) values ('Аберкромби Джо');
insert into authors (author) values ('Авдич Оса');
insert into authors (author) values ('Адамович Алесь');
insert into authors (author) values ('Адамс Дуглас');
insert into authors (author) values ('Адра Фред');
insert into authors (author) values ('Азарова Екатерина');
insert into authors (author) values ('Азимов Айзек');
insert into authors (author) values ('Айленд Стоун Тамара');
insert into authors (author) values ('Акунин Борис');
insert into authors (author) values ('Алейникова Юлия');
insert into authors (author) values ('Александер Ллойд');
insert into authors (author) values ('Александрова Наталья');
insert into authors (author) values ('Алексеев Михаил');
insert into authors (author) values ('Алексеев Сергей');
insert into authors (author) values ('Аллан Пиз');
insert into authors (author) values ('Алфеева Лина');
insert into authors (author) values ('Альенде Исабель');
insert into authors (author) values ('Алюшина Татьяна');
insert into authors (author) values ('Амен Дэниел Грегори');
insert into authors (author) values ('Амирезвани Анита');
insert into authors (author) values ('Андерсон Джоди Линн');
insert into authors (author) values ('Андерсон Марина');
insert into authors (author) values ('Андерсон Сара М.');
insert into authors (author) values ('Анджелис Барбара де');
insert into authors (author) values ('Андреев Алексей');
insert into authors (author) values ('Андреева Марина');
insert into authors (author) values ('Андрижески Дж. С.');
insert into authors (author) values ('Андросенко Александр');
insert into authors (author) values ('Анжело Алекс');
insert into authors (author) values ('Аннандейл Дэвид');
insert into authors (author) values ('Антонова Наталия');
insert into authors (author) values ('Анхем Стефан');
insert into authors (author) values ('Арден Кэтрин');
insert into authors (author) values ('Ардова Алиса');
insert into authors (author) values ('Ариели Дэн');
insert into authors (author) values ('Арифуллина Елена');
insert into authors (author) values ('Арментроут Дженнифер Л.');
insert into authors (author) values ('Арментроут Дженнифер Ли');
insert into authors (author) values ('Арнольд Дэвид');
insert into authors (author) values ('Арсан Эммануэль');
insert into authors (author) values ('Арсеньева Елена');
insert into authors (author) values ('Арто Паасилинна');
insert into authors (author) values ('Архангельская Мария');
insert into authors (author) values ('Арье Вера');
insert into authors (author) values ('Астапов Максим');
insert into authors (author) values ('Астахов Павел');
insert into authors (author) values ('Аствацатуров Андрей');
insert into authors (author) values ('Атаманов Михаил');
insert into authors (author) values ('Афанасьев Александр');
insert into authors (author) values ('Ахерн Сесилия');
insert into authors (author) values ('Байбаков Иван');
insert into authors (author) values ('Байер Уильям');
insert into authors (author) values ('Бакиров Анвар');
insert into authors (author) values ('Бакман Фредрик');
insert into authors (author) values ('Баковец Михаил');
insert into authors (author) values ('Баксбаум Джулия');
insert into authors (author) values ('Бакстер Стивен');
insert into authors (author) values ('Бакулина Екатерина');
insert into authors (author) values ('Балахнин Алексей');
insert into authors (author) values ('Балдаччи Дэвид');
insert into authors (author) values ('Баллерини Луиджи');
insert into authors (author) values ('Баневич Артур');
insert into authors (author) values ('Банзл Питер');
insert into authors (author) values ('Баранова Ирина');
insert into authors (author) values ('Барбара Пиз');
insert into authors (author) values ('Барбери Мюриель');
insert into authors (author) values ('Барден Фил');
insert into authors (author) values ('Бардуго Лей');
insert into authors (author) values ('Баринова Любовь');
insert into authors (author) values ('Барисо Джастин');
insert into authors (author) values ('Баркер Клайв');
insert into authors (author) values ('Баркер Хейли');
insert into authors (author) values ('Бармин Егор');
insert into authors (author) values ('Барнетт Дэвид');
insert into authors (author) values ('Барр Эмили');
insert into authors (author) values ('Барридж Джей Джей');
insert into authors (author) values ('Баррон Томас Арчибальд');
insert into authors (author) values ('Барчок Михаэль');
insert into authors (author) values ('Баскова Ольга');
insert into authors (author) values ('Батлук Анна');
insert into authors (author) values ('Батуман Элиф');
insert into authors (author) values ('Батырев Максим');
insert into authors (author) values ('Батыршин Борис');
insert into authors (author) values ('Башибузук Александр');
insert into authors (author) values ('Беверли Элизабет');
insert into authors (author) values ('Бегбедер Фредерик');
insert into authors (author) values ('Беденко Иван');
insert into authors (author) values ('Безбашенный');
insert into authors (author) values ('Бейли Роберт');
insert into authors (author) values ('Бекетт Саймон');
insert into authors (author) values ('Белл Алекс');
insert into authors (author) values ('Белл Логан');
insert into authors (author) values ('Беллэрс Джон');
insert into authors (author) values ('Беляков Алексей');
insert into authors (author) values ('Беляков Анатолий');
insert into authors (author) values ('Белянин Андрей');
insert into authors (author) values ('Бен Иззи Джоэл');
insert into authors (author) values ('Бендер Алекс');
insert into authors (author) values ('Бенджамин Артур');
insert into authors (author) values ('Беннет Джули');
insert into authors (author) values ('Беннетт М. А.');
insert into authors (author) values ('Беннетт Роберт Джексон');
insert into authors (author) values ('Бердж Рейчел');
insert into authors (author) values ('Бернелл Марк');
insert into authors (author) values ('Бернетт Дин');
insert into authors (author) values ('Берри Джулия');
insert into authors (author) values ('Берроуз Уильям Сьюард');
insert into authors (author) values ('Берч Хизер');
insert into authors (author) values ('Беспалова Екатерина');
insert into authors (author) values ('Бехари Тереза');
insert into authors (author) values ('Беяз Кати');
insert into authors (author) values ('Билик Дмитрий');
insert into authors (author) values ('Бити Эрин');
insert into authors (author) values ('Блайтон Энид');
insert into authors (author) values ('Бланк Эль');
insert into authors (author) values ('Блинова Маргарита');
insert into authors (author) values ('Блэк Холли');
insert into authors (author) values ('Бове Клементина');
insert into authors (author) values ('Богатырёв Александр');
insert into authors (author) values ('Богушева Валерия');
insert into authors (author) values ('Бойн Джон');
insert into authors (author) values ('Боланд Шалини');
insert into authors (author) values ('Болд Эмили');
insert into authors (author) values ('Болдова Марина');
insert into authors (author) values ('Болл Джесси');
insert into authors (author) values ('Большаков Валерий');
insert into authors (author) values ('Бон Маша');
insert into authors (author) values ('Бонд Гвенда');
insert into authors (author) values ('Бор Алекс');
insert into authors (author) values ('Борисов Константин');
insert into authors (author) values ('Бородин Алексей');
insert into authors (author) values ('Боталова Мария');
insert into authors (author) values ('Боуэн Сарина');
insert into authors (author) values ('Боуэн Элизабет');
insert into authors (author) values ('Брайт Мэлоди Элен');
insert into authors (author) values ('Бракен Александра');
insert into authors (author) values ('Браун Дэн');
insert into authors (author) values ('Браун Кристофер');
insert into authors (author) values ('Брегман Питер');
insert into authors (author) values ('Бреннан Мари');
insert into authors (author) values ('Бреннан-Джобс Лиза');
insert into authors (author) values ('Бринкманн Каролина');
insert into authors (author) values ('Брокманн Нина');
insert into authors (author) values ('Броуди Джессика');
insert into authors (author) values ('Брук Ридиан');
insert into authors (author) values ('Брукс Терри');
insert into authors (author) values ('Брындза Роберт');
insert into authors (author) values ('Брэдбери Рэй');
insert into authors (author) values ('Брэдли Алан');
insert into authors (author) values ('Буджолд Лоис МакМастер');
insert into authors (author) values ('Бузин Максим');
insert into authors (author) values ('Буланов Константин');
insert into authors (author) values ('Булгаков Михаил');
insert into authors (author) values ('Булганова Елена');
insert into authors (author) values ('Бурмистров Денис');
insert into authors (author) values ('Бурмистрова Екатерина');
insert into authors (author) values ('Бут Карен');
insert into authors (author) values ('Бут Стивен');
insert into authors (author) values ('Буша Александр');
insert into authors (author) values ('Бушар Сандра');
insert into authors (author) values ('Бушков Александр');
insert into authors (author) values ('Бушковский Александр');
insert into authors (author) values ('Бушуева Мария');
insert into authors (author) values ('Быков Дмитрий');
insert into authors (author) values ('Бьюкес Лорен');
insert into authors (author) values ('Бэнкрофт Джосайя');
insert into authors (author) values ('Бэнкс Майя');
insert into authors (author) values ('Бэрд Жаклин');
insert into authors (author) values ('Бэрроуз Энни');
insert into authors (author) values ('Вайн Барбара');
insert into authors (author) values ('Вайнштейн Стелла');
insert into authors (author) values ('Вайцкин Джош');
insert into authors (author) values ('Валенте Кэтрин М.');
insert into authors (author) values ('Валентеева Ольга');
insert into authors (author) values ('Валериев Игорь');
insert into authors (author) values ('Валерия Вербинина');
insert into authors (author) values ('Ван Бой Саймон');
insert into authors (author) values ('Вапник Эмили');
insert into authors (author) values ('Варгас Фред');
insert into authors (author) values ('Варго Александр');
insert into authors (author) values ('Вардунас Игорь');
insert into authors (author) values ('Василенко Владимир');
insert into authors (author) values ('Васильев Александр');
insert into authors (author) values ('Васильев Андрей');
insert into authors (author) values ('Васина Екатерина');
insert into authors (author) values ('Васкес-Фигероа Альберто');
insert into authors (author) values ('Вафин Юрий');
insert into authors (author) values ('Вахненко Федор');
insert into authors (author) values ('Веббер Кэтрин');
insert into authors (author) values ('Вебер Бернард');
insert into authors (author) values ('Вега Даниэль');
insert into authors (author) values ('Вейр Энди');
insert into authors (author) values ('Веласкес-Манофф Мойзес');
insert into authors (author) values ('Велес Анна');
insert into authors (author) values ('Величко Андрей');
insert into authors (author) values ('Вентворт Патриция');
insert into authors (author) values ('Вербер Бернар');
insert into authors (author) values ('Вербинина Валерия');
insert into authors (author) values ('Вереснев Игорь');
insert into authors (author) values ('Веркин Эдуард');
insert into authors (author) values ('Верн Жюль');
insert into authors (author) values ('Верхова Екатерина');
insert into authors (author) values ('Весенняя Марина');
insert into authors (author) values ('Ветреная Инга');
insert into authors (author) values ('Вида Вендела');
insert into authors (author) values ('Винд Кристиан Роберт');
insert into authors (author) values ('Виндж Вернор Стеффан');
insert into authors (author) values ('Витгенштейн Людвиг');
insert into authors (author) values ('Вишневская Галина');
insert into authors (author) values ('Вишневский Януш');
insert into authors (author) values ('Владимиров Александр');
insert into authors (author) values ('Владимиров Денис');
insert into authors (author) values ('Водолазкин Евгений');
insert into authors (author) values ('Волгина Надежда');
insert into authors (author) values ('Волков Александр');
insert into authors (author) values ('Волков Тим');
insert into authors (author) values ('Волкова Светлана');
insert into authors (author) values ('Вольлебен Петер');
insert into authors (author) values ('Вольт Анастасия');
insert into authors (author) values ('Вольф Клаус-Петер');
insert into authors (author) values ('Воннегут Курт');
insert into authors (author) values ('Воронков Алексей');
insert into authors (author) values ('Воронова Мария');
insert into authors (author) values ('Воронцов Александр');
insert into authors (author) values ('Вострова Екатерина');
insert into authors (author) values ('Врочек Шимун');
insert into authors (author) values ('Вуд Алекс');
insert into authors (author) values ('Вуд Джосс');
insert into authors (author) values ('Вудворт Франциска');
insert into authors (author) values ('Вудфайн Кэтрин');
insert into authors (author) values ('Вулф Вирджиния');
insert into authors (author) values ('Вулф Терри');
insert into authors (author) values ('Вулф Тобиас');
insert into authors (author) values ('Выборнов Наиль');
insert into authors (author) values ('Выставной Владислав');
insert into authors (author) values ('Вязовский Алексей');
insert into authors (author) values ('Габсер Стивен');
insert into authors (author) values ('Гаврилова Анна');
insert into authors (author) values ('Гаглоев Евгений');
insert into authors (author) values ('Гайдукевич Владислав');
insert into authors (author) values ('Гайдукова Людмила');
insert into authors (author) values ('Гальеро Рубен Давид Гонсалес');
insert into authors (author) values ('Ганин Илья');
insert into authors (author) values ('Гарбера Кэтрин');
insert into authors (author) values ('Гарди Томас');
insert into authors (author) values ('Гарсиа Маркес Габриэль');
insert into authors (author) values ('Гедеон Александр');
insert into authors (author) values ('Гейман Нил');
insert into authors (author) values ('Гем Франциска');
insert into authors (author) values ('Генис Александр');
insert into authors (author) values ('Генри Кристина');
insert into authors (author) values ('Гептинг Кристина');
insert into authors (author) values ('Геральт Николай');
insert into authors (author) values ('Герасимова Галина');
insert into authors (author) values ('Герман Юлия');
insert into authors (author) values ('Герритсен Тесс');
insert into authors (author) values ('Геярова Ная');
insert into authors (author) values ('Гжендович Ярослав');
insert into authors (author) values ('Гилберт Элизабет');
insert into authors (author) values ('Гилберт Энтони');
insert into authors (author) values ('Гиппенрейтер Юлия');
insert into authors (author) values ('Гир Керстин');
insert into authors (author) values ('Глайнс Эбби');
insert into authors (author) values ('Глебов Виктор');
insert into authors (author) values ('Глебов Макс');
insert into authors (author) values ('Глинина Оксана');
insert into authors (author) values ('Глушановский Алексей');
insert into authors (author) values ('Говард Элизабет Джейн');
insert into authors (author) values ('Гоголь Николай');
insert into authors (author) values ('Годин Сет');
insert into authors (author) values ('Голдберг Дэнни');
insert into authors (author) values ('Голден Кристи');
insert into authors (author) values ('Голден Кристофер');
insert into authors (author) values ('Головачёв Василий');
insert into authors (author) values ('Голубева Александра');
insert into authors (author) values ('Гольман Иосиф');
insert into authors (author) values ('Гончарова Галина');
insert into authors (author) values ('Гончарова Марианна');
insert into authors (author) values ('Гопник Элисон');
insert into authors (author) values ('Горбунова Екатерина');
insert into authors (author) values ('Горелик Людмила');
insert into authors (author) values ('Горцев Николай');
insert into authors (author) values ('Готтман Джон');
insert into authors (author) values ('Готтсман Диана');
insert into authors (author) values ('Гоулман Дэниел');
insert into authors (author) values ('Грабовский Роман');
insert into authors (author) values ('Гранже Жан-Кристоф');
insert into authors (author) values ('Гранже Жан—Кристоф');
insert into authors (author) values ('Гранн Дэвид');
insert into authors (author) values ('Грант Адам');
insert into authors (author) values ('Грант Майкл');
insert into authors (author) values ('Грегори Филиппа');
insert into authors (author) values ('Грей Амелия');
insert into authors (author) values ('Грей Джон');
insert into authors (author) values ('Грей Питер');
insert into authors (author) values ('Грей Саша');
insert into authors (author) values ('Грей Стелла');
insert into authors (author) values ('Грейвс Пола');
insert into authors (author) values ('Греттон Тесса');
insert into authors (author) values ('Грехем Анджела');
insert into authors (author) values ('Грибоедов Александр');
insert into authors (author) values ('Грин Джон');
insert into authors (author) values ('Грин Салли');
insert into authors (author) values ('Грин Эбби');
insert into authors (author) values ('Грин Эллен');
insert into authors (author) values ('Грин Эмилия');
insert into authors (author) values ('Гришанин Дмитрий');
insert into authors (author) values ('Гришевский Анджей');
insert into authors (author) values ('Гришин Алексей');
insert into authors (author) values ('Гришэм Джон');
insert into authors (author) values ('Гродин Райан');
insert into authors (author) values ('Громова Наталья');
insert into authors (author) values ('Гросс-Ло Кристина');
insert into authors (author) values ('Гроссман Давид');
insert into authors (author) values ('Грубер Андреас');
insert into authors (author) values ('Грэй Джон');
insert into authors (author) values ('Грэм Маргарет');
insert into authors (author) values ('Грэхем Линн');
insert into authors (author) values ('Гувер Колин');
insert into authors (author) values ('Гундар-Гушан Айелет');
insert into authors (author) values ('Гунель Лоран');
insert into authors (author) values ('Гусейнова Ольга');
insert into authors (author) values ('Гэблдон Диана');
insert into authors (author) values ('Гэлбрейт Роберт');
insert into authors (author) values ('Гюго Виктор');
insert into authors (author) values ('Далчер Кристина');
insert into authors (author) values ('Даль Арне');
insert into authors (author) values ('Даль Дмитрий');
insert into authors (author) values ('Даль Роальд');
insert into authors (author) values ('Данильченко Олег');
insert into authors (author) values ('Данкер Патрисия');
insert into authors (author) values ('Данлоп Барбара');
insert into authors (author) values ('Данн Дженси');
insert into authors (author) values ('Данн Кэтрин');
insert into authors (author) values ('Данфорд Кэролайн');
insert into authors (author) values ('Дарья Калинина');
insert into authors (author) values ('Даунинг Саманта');
insert into authors (author) values ('Дашевская Анна');
insert into authors (author) values ('Дашкова Полина');
insert into authors (author) values ('Дворецкая Елизавета');
insert into authors (author) values ('Де Лакло Шодерло');
insert into authors (author) values ('Де Сент-Экзюпери Антуан');
insert into authors (author) values ('Де Фомбель Тимоте');
insert into authors (author) values ('Дедерер Клер');
insert into authors (author) values ('Делакруз Алекс');
insert into authors (author) values ('Делейни Дж. П.');
insert into authors (author) values ('Делон Дана');
insert into authors (author) values ('Демидов Александр');
insert into authors (author) values ('Демина Карина');
insert into authors (author) values ('Демченко Антон');
insert into authors (author) values ('Денин Брендан');
insert into authors (author) values ('Деннинг Стивен');
insert into authors (author) values ('Детвейлер Кейтлин');
insert into authors (author) values ('Джей-Джонс С.');
insert into authors (author) values ('Джеймс Билл');
insert into authors (author) values ('Джеймс Вик');
insert into authors (author) values ('Джеймс Марлон');
insert into authors (author) values ('Джеймс Питер');
insert into authors (author) values ('Джеймс Эрика Леонард');
insert into authors (author) values ('Джейн Анна');
insert into authors (author) values ('Джексон Нина');
insert into authors (author) values ('Джемисин Нора К.');
insert into authors (author) values ('Джеппсен Трэвис');
insert into authors (author) values ('Джи Уитни');
insert into authors (author) values ('Джиллиан Алекс');
insert into authors (author) values ('Джио Сара');
insert into authors (author) values ('Джонс Джей Сидни');
insert into authors (author) values ('Джонс Диана Уинн');
insert into authors (author) values ('Джонс Н. Г.');
insert into authors (author) values ('Джонсон Джордж Клейтон');
insert into authors (author) values ('Джонсон Дэйзи');
insert into authors (author) values ('Джонсон Эбигейл');
insert into authors (author) values ('Джордан Роберт');
insert into authors (author) values ('Дивер Джеффри');
insert into authors (author) values ('Диккер Жоэль');
insert into authors (author) values ('ДиТерлицци Тони');
insert into authors (author) values ('Дмитриев Павел');
insert into authors (author) values ('Долинин Александр');
insert into authors (author) values ('Долонь Мария');
insert into authors (author) values ('Донн К. Л.');
insert into authors (author) values ('Доннелли Деннифер');
insert into authors (author) values ('Доннелли Дженнифер');
insert into authors (author) values ('Донцова Дарья');
insert into authors (author) values ('Дорн Вульф');
insert into authors (author) values ('Достоевский Федор');
insert into authors (author) values ('Дотри Микки');
insert into authors (author) values ('Доусон Натали');
insert into authors (author) values ('Драгунский Виктор');
insert into authors (author) values ('Дрейвен Грейс');
insert into authors (author) values ('Дронт Николай');
insert into authors (author) values ('Дубинина Мария');
insert into authors (author) values ('Думчев Артур');
insert into authors (author) values ('Дункан Фрэнсис');
insert into authors (author) values ('Дункан Эмили А.');
insert into authors (author) values ('Духовны Дэвид');
insert into authors (author) values ('Дьюал Эшли Энн');
insert into authors (author) values ('Дьюк Энни');
insert into authors (author) values ('Дэй Сильвия');
insert into authors (author) values ('Дэмпси Оуэн');
insert into authors (author) values ('Дэорсе Александр');
insert into authors (author) values ('Дюжева Маргарита');
insert into authors (author) values ('Дюран Сабин');
insert into authors (author) values ('Евгенидис Джеффри');
insert into authors (author) values ('Евглевский Яков');
insert into authors (author) values ('Евдокимов Дмитрий');
insert into authors (author) values ('Егоров Валентин');
insert into authors (author) values ('Егорова Татьяна');
insert into authors (author) values ('Егорова Яна');
insert into authors (author) values ('Ежова Лана');
insert into authors (author) values ('Ейтс Мейси');
insert into authors (author) values ('Елисеев Михаил');
insert into authors (author) values ('Емельянов Антон');
insert into authors (author) values ('Емец Дмитрий');
insert into authors (author) values ('Еналь Варвара');
insert into authors (author) values ('Ермаков Михаил');
insert into authors (author) values ('Етоев Александр');
insert into authors (author) values ('Ефиминюк Марина');
insert into authors (author) values ('Ефимова Юлия');
insert into authors (author) values ('Жаворски Жан-Филипп');
insert into authors (author) values ('Жвалевский Андрей');
insert into authors (author) values ('Жванецкий Михаил');
insert into authors (author) values ('Жданова Светлана');
insert into authors (author) values ('Желнов Валерий');
insert into authors (author) values ('Желунов Николай');
insert into authors (author) values ('Жеребьёв Владислав');
insert into authors (author) values ('Жибель Карин');
insert into authors (author) values ('Жильцова Наталья');
insert into authors (author) values ('Жмак Валерий');
insert into authors (author) values ('Журавская Светлана');
insert into authors (author) values ('Жуффа Сюзи');
insert into authors (author) values ('Забелин Максим');
insert into authors (author) values ('Завойчинская Милена');
insert into authors (author) values ('Замлелова Светлана');
insert into authors (author) values ('Запата Мариана');
insert into authors (author) values ('Звездная Елена');
insert into authors (author) values ('Зверев Сергей');
insert into authors (author) values ('Зволинская Ирина');
insert into authors (author) values ('Звонцова Екатерина');
insert into authors (author) values ('Зелинская Ляна');
insert into authors (author) values ('Зеталер Роберт');
insert into authors (author) values ('Зещинский Владимир');
insert into authors (author) values ('Злотников Роман');
insert into authors (author) values ('Зомороди Мануш');
insert into authors (author) values ('Зотов Степан');
insert into authors (author) values ('Зузак Маркус');
insert into authors (author) values ('Зурков Дмитрий');
insert into authors (author) values ('Зусак Маркус');
insert into authors (author) values ('Зыков Виталий');
insert into authors (author) values ('Зюскинд Патрик');
insert into authors (author) values ('Ибрагим Зак');
insert into authors (author) values ('Иванов Алексей');
insert into authors (author) values ('Иванова Ольга');
insert into authors (author) values ('Иванович Юрий');
insert into authors (author) values ('Ивах Светлана');
insert into authors (author) values ('Иггульден Конн');
insert into authors (author) values ('Иден Синтия');
insert into authors (author) values ('Идиатуллин Шамиль');
insert into authors (author) values ('Измайлова Кира');
insert into authors (author) values ('Изюмская Анастасия');
insert into authors (author) values ('Ильин Андрей');
insert into authors (author) values ('Ильин Владимир');
insert into authors (author) values ('Ильюшина Лилия');
insert into authors (author) values ('Ильяхов Максим');
insert into authors (author) values ('Именитов Евгений');
insert into authors (author) values ('Ирвин Алекс');
insert into authors (author) values ('Итцлер Джесси');
insert into authors (author) values ('Йап Фелисия');
insert into authors (author) values ('Йохансен Эрика');
insert into authors (author) values ('Каблукова Екатерина');
insert into authors (author) values ('Кабони Кристина');
insert into authors (author) values ('Кабре Жауме');
insert into authors (author) values ('Кагава Джули');
insert into authors (author) values ('Казакова Светлана');
insert into authors (author) values ('Казанков Александр');
insert into authors (author) values ('Казьмин Михаил');
insert into authors (author) values ('Калашников Сергей');
insert into authors (author) values ('Калбазов Константин');
insert into authors (author) values ('Калинин Даниил');
insert into authors (author) values ('Калинина Дарья');
insert into authors (author) values ('Калинкина Анна');
insert into authors (author) values ('Каллентофт Монс');
insert into authors (author) values ('Кальберак Иван');
insert into authors (author) values ('Каменев Алекс');
insert into authors (author) values ('Каменистый Артем');
insert into authors (author) values ('Камю Альбер');
insert into authors (author) values ('Кандела Ольга');
insert into authors (author) values ('Као Ирэне');
insert into authors (author) values ('Карамзин Николай');
insert into authors (author) values ('Карасев Василий');
insert into authors (author) values ('Карлино Рене');
insert into authors (author) values ('Кароль Елена');
insert into authors (author) values ('Карпентер Тереза');
insert into authors (author) values ('Карпин Дмитрий');
insert into authors (author) values ('Карпович Ольга');
insert into authors (author) values ('Карр Аллен');
insert into authors (author) values ('Карризи Донато');
insert into authors (author) values ('Каст Бас');
insert into authors (author) values ('Каст Кристин');
insert into authors (author) values ('Каст Филис Кристина');
insert into authors (author) values ('Кастен Мона');
insert into authors (author) values ('Кау Игер');
insert into authors (author) values ('Кахелин Дэниэл');
insert into authors (author) values ('Кван Кевин');
insert into authors (author) values ('Кеворкян Константин');
insert into authors (author) values ('Кей Маргарет');
insert into authors (author) values ('Кейн Алекс');
insert into authors (author) values ('Кейн Рэйчел');
insert into authors (author) values ('Кейнс Катрина');
insert into authors (author) values ('Келли Ванесса');
insert into authors (author) values ('Келли Линн');
insert into authors (author) values ('Кельт Владимир');
insert into authors (author) values ('Кельт Ян');
insert into authors (author) values ('Кеммерер Бриджид');
insert into authors (author) values ('Кенан Лорин');
insert into authors (author) values ('Кендрик Шэрон');
insert into authors (author) values ('Кеннеди Гэвин');
insert into authors (author) values ('Кеннеди Элли');
insert into authors (author) values ('Кеннеди Эль');
insert into authors (author) values ('Кенэли Томас');
insert into authors (author) values ('Кеплингер Коди');
insert into authors (author) values ('Кепнес Кэролайн');
insert into authors (author) values ('Керлис Пальмира');
insert into authors (author) values ('Кехо Джон');
insert into authors (author) values ('Кид Сью Монк');
insert into authors (author) values ('Киз Дэниел');
insert into authors (author) values ('Кийосаки Роберт');
insert into authors (author) values ('Киланд Ви');
insert into authors (author) values ('Ким Джон');
insert into authors (author) values ('Кин Кэролайн');
insert into authors (author) values ('Кинг Лили');
insert into authors (author) values ('Кинг Стивен');
insert into authors (author) values ('Кинселла Софи');
insert into authors (author) values ('Кинси Ти');
insert into authors (author) values ('Кирьянова Анна');
insert into authors (author) values ('Кларк Колин');
insert into authors (author) values ('Кларк Люси');
insert into authors (author) values ('Клевер Алиса');
insert into authors (author) values ('Клевир Анна');
insert into authors (author) values ('Клейнман Пол');
insert into authors (author) values ('Клейтон Дониэль');
insert into authors (author) values ('Клещенко Елена');
insert into authors (author) values ('Клима Габриэле');
insert into authors (author) values ('Клоско Джанет');
insert into authors (author) values ('Клусс Джессика');
insert into authors (author) values ('Клэйр Ребекка');
insert into authors (author) values ('Клэр Гвендолин');
insert into authors (author) values ('Клэр Кассандра');
insert into authors (author) values ('Кнолл Джессика');
insert into authors (author) values ('Кнудсен Сверре');
insert into authors (author) values ('Князева Анна');
insert into authors (author) values ('Кобен Харлан');
insert into authors (author) values ('Ковалева Виктория');
insert into authors (author) values ('Коган Татьяна');
insert into authors (author) values ('Когман Женевьева');
insert into authors (author) values ('Козлов Иван');
insert into authors (author) values ('Кокс Жозефина');
insert into authors (author) values ('Кокс Мэгги');
insert into authors (author) values ('Колина Елена');
insert into authors (author) values ('Коллектив авторов');
insert into authors (author) values ('Колочкова Вера');
insert into authors (author) values ('Колфер Крис');
insert into authors (author) values ('Колфер Оуэн');
insert into authors (author) values ('Колычев Владимир');
insert into authors (author) values ('Колышко Иосиф');
insert into authors (author) values ('Колюжняк Виктор');
insert into authors (author) values ('Комарова Ирина');
insert into authors (author) values ('Конде Мариз');
insert into authors (author) values ('Кондор Вилмош');
insert into authors (author) values ('Кондратьев Вячеслав');
insert into authors (author) values ('Конофальский Борис');
insert into authors (author) values ('Конторович Александр');
insert into authors (author) values ('Конюшевский Владислав');
insert into authors (author) values ('Корецкий Данил');
insert into authors (author) values ('Корита Майкл');
insert into authors (author) values ('Корн Владимир');
insert into authors (author) values ('Корнакова Елена');
insert into authors (author) values ('Корнатовский Николай');
insert into authors (author) values ('Корнев Павел');
insert into authors (author) values ('Корнуэлл Бернард');
insert into authors (author) values ('Коротков Сергей');
insert into authors (author) values ('Коротков Юрий');
insert into authors (author) values ('Корпс Бризин');
insert into authors (author) values ('Корр Катрин');
insert into authors (author) values ('Корсакова Татьяна');
insert into authors (author) values ('Корчагина Мария');
insert into authors (author) values ('Корчевский Юрий');
insert into authors (author) values ('Косухина Наталья');
insert into authors (author) values ('Котлер Филип');
insert into authors (author) values ('Котов Алексей');
insert into authors (author) values ('Коттон Рейчел');
insert into authors (author) values ('Коу Джонатан');
insert into authors (author) values ('Коул Тилли');
insert into authors (author) values ('Коуст Дора');
insert into authors (author) values ('Коханенко Ольга');
insert into authors (author) values ('Кош Алекс');
insert into authors (author) values ('Кошкарев Ян');
insert into authors (author) values ('Коэльо Пауло');
insert into authors (author) values ('Крамер Марина');
insert into authors (author) values ('Крамер Стейс');
insert into authors (author) values ('Краснахоркаи Ласло');
insert into authors (author) values ('Красников Андрей');
insert into authors (author) values ('Красницкий Евгений');
insert into authors (author) values ('Крауч Блейк');
insert into authors (author) values ('Крауч Джени');
insert into authors (author) values ('Крейвен Сара');
insert into authors (author) values ('Крейг Эрин');
insert into authors (author) values ('Крейс Джим');
insert into authors (author) values ('Криббс Джиа');
insert into authors (author) values ('Кривонос Виталий');
insert into authors (author) values ('Криспин Энн Кэрол');
insert into authors (author) values ('Кристенс Инге');
insert into authors (author) values ('Кристи Агата');
insert into authors (author) values ('Кристофер Адам');
insert into authors (author) values ('Кристофф Джей');
insert into authors (author) values ('Крич Шарон');
insert into authors (author) values ('Кронин Джастин');
insert into authors (author) values ('Кроули Джорджи');
insert into authors (author) values ('Круз Андрей');
insert into authors (author) values ('Крыжановская-Рочестер Вера');
insert into authors (author) values ('Крыжановский Михаил');
insert into authors (author) values ('Крылова Светлана');
insert into authors (author) values ('Крымов Илья');
insert into authors (author) values ('Крюков Андрей');
insert into authors (author) values ('Ксандер Майкл');
insert into authors (author) values ('Кузнецов Сергей');
insert into authors (author) values ('Кузнецова Дарья');
insert into authors (author) values ('Кузнечихин Сергей');
insert into authors (author) values ('Кузьмина Надежда');
insert into authors (author) values ('Кук Глен Чарльз');
insert into authors (author) values ('Кук Эйлен');
insert into authors (author) values ('Кулыгина Дарья');
insert into authors (author) values ('Кумин Вячеслав');
insert into authors (author) values ('Кунц Дин');
insert into authors (author) values ('Купер Рокси');
insert into authors (author) values ('Курган Сергей');
insert into authors (author) values ('Курилкин Матвей');
insert into authors (author) values ('Курпатов Андрей');
insert into authors (author) values ('Куц Сергей');
insert into authors (author) values ('Кушнер Рейчел');
insert into authors (author) values ('Кэдри Ричард');
insert into authors (author) values ('Кэйбелл Крейг');
insert into authors (author) values ('Кэлус Мишель');
insert into authors (author) values ('Кэрол Джеймс');
insert into authors (author) values ('Кэрролл Льюис');
insert into authors (author) values ('Кэссиди Карла');
insert into authors (author) values ('Л Энгл Мадлен');
insert into authors (author) values ('Лав Фрэнки');
insert into authors (author) values ('Лаваль Виктор');
insert into authors (author) values ('Лавкрафт Говард Филлипс');
insert into authors (author) values ('Лавринович Ася');
insert into authors (author) values ('Лавринович Ася');
insert into authors (author) values ('Лавров Валентин');
insert into authors (author) values ('Лагеркранц Давид');
insert into authors (author) values ('Лагерлёф Сельма');
insert into authors (author) values ('Лазарев Дмитрий');
insert into authors (author) values ('Лазарева Молка');
insert into authors (author) values ('Лазарус Дин Маргарет');
insert into authors (author) values ('Лайм Сильвия');
insert into authors (author) values ('Лайонс Мишель');
insert into authors (author) values ('Лайтман Алан');
insert into authors (author) values ('Лакина Ирина');
insert into authors (author) values ('Лакс Айрин');
insert into authors (author) values ('Лакс Евгений');
insert into authors (author) values ('Ланитова Лана');
insert into authors (author) values ('Лансдейл Джо Р.');
insert into authors (author) values ('Ланцов Михаил');
insert into authors (author) values ('Лапенья Шери');
insert into authors (author) values ('Ларвуд Киран');
insert into authors (author) values ('Лаурен Анна-Лена');
insert into authors (author) values ('Ле Карре Джон');
insert into authors (author) values ('Лебедев Игорь');
insert into authors (author) values ('Левандовский Борис');
insert into authors (author) values ('Леви Марк');
insert into authors (author) values ('Левина Нина');
insert into authors (author) values ('Левченко Александр');
insert into authors (author) values ('Лей Тара');
insert into authors (author) values ('Лейк Оливия');
insert into authors (author) values ('Леклезио Жан-Мари Гюстав');
insert into authors (author) values ('Лелич Саймон');
insert into authors (author) values ('Лелчек Сол');
insert into authors (author) values ('Лемерт Пьер');
insert into authors (author) values ('Ленцева Рада');
insert into authors (author) values ('Леонов Николай');
insert into authors (author) values ('Лерман Мэгги');
insert into authors (author) values ('Лернер Харриет');
insert into authors (author) values ('Леруа Арман Мари');
insert into authors (author) values ('Лесина Екатерина');
insert into authors (author) values ('Лесли Алекс');
insert into authors (author) values ('Ли Фонда');
insert into authors (author) values ('Ли Харпер');
insert into authors (author) values ('Либих Александр');
insert into authors (author) values ('Лиленко-Карелина Ирина');
insert into authors (author) values ('Лилит Диана');
insert into authors (author) values ('Лим Элизабет');
insert into authors (author) values ('Линдберг Энн');
insert into authors (author) values ('Линдгрен Астрид');
insert into authors (author) values ('Линдквист Йон Айвиде');
insert into authors (author) values ('Линдсей Джоанна');
insert into authors (author) values ('Линдсей Дэвид');
insert into authors (author) values ('Линдсей Ивонн');
insert into authors (author) values ('Лисина Александра');
insert into authors (author) values ('Лисьев Андрей');
insert into authors (author) values ('Литвак Борис');
insert into authors (author) values ('Литвинова Анна');
insert into authors (author) values ('Литвиновы Анна и Сергей');
insert into authors (author) values ('Литкотт—Хеймс Джули');
insert into authors (author) values ('Литтл Бентли');
insert into authors (author) values ('Лихи Роберт');
insert into authors (author) values ('Лобанов Александр');
insert into authors (author) values ('Логвин Янина');
insert into authors (author) values ('Логинов Михаил');
insert into authors (author) values ('Логинова Светлана');
insert into authors (author) values ('Лозовская Адель');
insert into authors (author) values ('Лонг Беверли');
insert into authors (author) values ('Лондон Джек');
insert into authors (author) values ('Лонсдейл Кэрри');
insert into authors (author) values ('Лопато Семен');
insert into authors (author) values ('Лоранс Камилла');
insert into authors (author) values ('Лорен Антуан');
insert into authors (author) values ('Лорен Кристина');
insert into authors (author) values ('Лоренс Ким');
insert into authors (author) values ('Лори Хью');
insert into authors (author) values ('Лосада Изабель');
insert into authors (author) values ('Лоу Том');
insert into authors (author) values ('Лошкарёва Виктория');
insert into authors (author) values ('Лу Мари');
insert into authors (author) values ('Луганцева Татьяна');
insert into authors (author) values ('Лукас Дженни');
insert into authors (author) values ('Лукашевич Анна');
insert into authors (author) values ('Лукьяненко Сергей');
insert into authors (author) values ('Лундберг София');
insert into authors (author) values ('Лурье Лев');
insert into authors (author) values ('Льюис Сьюзен');
insert into authors (author) values ('Лэкберг Камилла');
insert into authors (author) values ('Лэки Мерседес');
insert into authors (author) values ('Лэнг Наталья');
insert into authors (author) values ('Лэндей Уильям');
insert into authors (author) values ('Любимка Настя');
insert into authors (author) values ('Людвиг Петр');
insert into authors (author) values ('Люпо Кесия');
insert into authors (author) values ('Лях Андрей');
insert into authors (author) values ('Маас Сара Дж.');
insert into authors (author) values ('Магари Дрю');
insert into authors (author) values ('Мазин Александр');
insert into authors (author) values ('Майер Кай');
insert into authors (author) values ('Майер Марисса');
insert into authors (author) values ('Майер Стефани');
insert into authors (author) values ('Майка Павел');
insert into authors (author) values ('Макарова Людмила');
insert into authors (author) values ('Макафи Эндрю');
insert into authors (author) values ('Макбрайд Стюарт');
insert into authors (author) values ('Макгвайр Джейми');
insert into authors (author) values ('Макгонигал Келли');
insert into authors (author) values ('Макгрегор Джоанн');
insert into authors (author) values ('МакГэрри Кэти');
insert into authors (author) values ('Макеев Алексей');
insert into authors (author) values ('Макинтош Софи');
insert into authors (author) values ('Маккарти Джеймс Рейчел');
insert into authors (author) values ('Маккарти Кормак');
insert into authors (author) values ('Маккей Мэтью');
insert into authors (author) values ('Маккеллен Кристи');
insert into authors (author) values ('Маккензи Роберт');
insert into authors (author) values ('Маккинти Эдриан');
insert into authors (author) values ('Макманус Карен М.');
insert into authors (author) values ('Максимов Макс');
insert into authors (author) values ('Максимов Рустам');
insert into authors (author) values ('Макфолл Клэр');
insert into authors (author) values ('Макьюэн Иэн');
insert into authors (author) values ('Малиновская Елена');
insert into authors (author) values ('Малкиел Бертон');
insert into authors (author) values ('Малышева Антонина');
insert into authors (author) values ('Мамаева Надежда');
insert into authors (author) values ('Мамонтов Павел');
insert into authors (author) values ('Манасыпов Дмитрий');
insert into authors (author) values ('Манзор Рене');
insert into authors (author) values ('Манкастер Гарриет');
insert into authors (author) values ('Манн Игорь');
insert into authors (author) values ('Манн Кэтрин');
insert into authors (author) values ('Мараис Бьянка');
insert into authors (author) values ('Маринина Александра');
insert into authors (author) values ('Маришин Михаил');
insert into authors (author) values ('Мария Круз');
insert into authors (author) values ('Марклунд Лиза');
insert into authors (author) values ('Маррс Джон');
insert into authors (author) values ('Марсонс Анжела');
insert into authors (author) values ('Март');
insert into authors (author) values ('Мартел Янн');
insert into authors (author) values ('Мартен-Люган Аньес');
insert into authors (author) values ('Мартин Джордж');
insert into authors (author) values ('Мартин Чарльз');
insert into authors (author) values ('Мартинес Али');
insert into authors (author) values ('Мартинович Виктор');
insert into authors (author) values ('Мартова Людмила');
insert into authors (author) values ('Мартынов Илья');
insert into authors (author) values ('Марченко Андрей');
insert into authors (author) values ('Марченко Геннадий');
insert into authors (author) values ('Марчетта Мелина');
insert into authors (author) values ('Марчук Николай');
insert into authors (author) values ('Марш Найо');
insert into authors (author) values ('Маршенкулова Залина');
insert into authors (author) values ('Маскейм Эстель');
insert into authors (author) values ('Мастрюкова Татьяна');
insert into authors (author) values ('Матешко Анастасия');
insert into authors (author) values ('Матисов Павел');
insert into authors (author) values ('Мафи Тахера');
insert into authors (author) values ('Мах Макс');
insert into authors (author) values ('Махавкин Анатолий');
insert into authors (author) values ('Маццола Кристен Хоуп');
insert into authors (author) values ('Машкова Диана');
insert into authors (author) values ('Медведева Алена');
insert into authors (author) values ('Медоус Дейзи');
insert into authors (author) values ('Мейер Джоанна Рут');
insert into authors (author) values ('Мейер Марисса');
insert into authors (author) values ('Мейер Сьюзен');
insert into authors (author) values ('Мейл Питер');
insert into authors (author) values ('Мелан Вероника');
insert into authors (author) values ('Меллик-третий Карлтон');
insert into authors (author) values ('Мельнюшкин Вадим');
insert into authors (author) values ('Меньщикова Татьяна');
insert into authors (author) values ('Мерфи Моника');
insert into authors (author) values ('Мессенджер Шеннон');
insert into authors (author) values ('Метельский Николай');
insert into authors (author) values ('Метлицкая Мария');
insert into authors (author) values ('Миклашевская Ольга');
insert into authors (author) values ('Миконов Дмитрий');
insert into authors (author) values ('Миленина Лидия');
insert into authors (author) values ('Миллер Джеффри');
insert into authors (author) values ('Миллер Кэтлин');
insert into authors (author) values ('Миллс Эмма');
insert into authors (author) values ('Милн Нина');
insert into authors (author) values ('Минаева Анна');
insert into authors (author) values ('Минин Андрей');
insert into authors (author) values ('Минц Лори');
insert into authors (author) values ('Миньер Бернар');
insert into authors (author) values ('Миранда Меган');
insert into authors (author) values ('Миронов Алексей');
insert into authors (author) values ('Миронов Вячеслав');
insert into authors (author) values ('Миронова Александра');
insert into authors (author) values ('Мирум Юта');
insert into authors (author) values ('Митчелл Дэвид');
insert into authors (author) values ('Михайлов Максим');
insert into authors (author) values ('Михайлова Евгения');
insert into authors (author) values ('Михайлова Екатерина');
insert into authors (author) values ('Михайловский Александр');
insert into authors (author) values ('Михаэлидес Алекс');
insert into authors (author) values ('Михеев Михаил');
insert into authors (author) values ('Михеев Сергей');
insert into authors (author) values ('Мичел П. Т.');
insert into authors (author) values ('Мичи Анна');
insert into authors (author) values ('Мишин Виктор');
insert into authors (author) values ('Моби');
insert into authors (author) values ('Модестов Николай');
insert into authors (author) values ('Мозли Фиона');
insert into authors (author) values ('Мойес Джоджо');
insert into authors (author) values ('Мойес Патриция');
insert into authors (author) values ('Монро Дж. С.');
insert into authors (author) values ('Моран Брайан');
insert into authors (author) values ('Морган Ричард К.');
insert into authors (author) values ('Морган Сара');
insert into authors (author) values ('Мори Юрий');
insert into authors (author) values ('Мориарти Лиана');
insert into authors (author) values ('Морриган Барбара');
insert into authors (author) values ('Моррилл Лорен');
insert into authors (author) values ('Моррисон Грант');
insert into authors (author) values ('Мортимер Кэрол');
insert into authors (author) values ('Мортон Кейт');
insert into authors (author) values ('Мортон Эндрю');
insert into authors (author) values ('Москаленко Юрий');
insert into authors (author) values ('Москвин Игорь');
insert into authors (author) values ('Мосс Кейт');
insert into authors (author) values ('Мофина Рик');
insert into authors (author) values ('Мошфег Отесса');
insert into authors (author) values ('Мукерджи Нил');
insert into authors (author) values ('Мур Стюарт');
insert into authors (author) values ('Муравьев Константин');
insert into authors (author) values ('Мураками Харуки');
insert into authors (author) values ('Мусиенко Вячеслав');
insert into authors (author) values ('Мьевилль Чайна');
insert into authors (author) values ('Мьюир Элис');
insert into authors (author) values ('Мэзер Адриана');
insert into authors (author) values ('Мэйберри Джонатан');
insert into authors (author) values ('Мэйджер Энн');
insert into authors (author) values ('Мюссо Гийом');
insert into authors (author) values ('Мясоедов Владимир');
insert into authors (author) values ('Набоков Владимир');
insert into authors (author) values ('Набокова Ника');
insert into authors (author) values ('Наваи Рамита');
insert into authors (author) values ('Надал Рафел');
insert into authors (author) values ('Найт Рени');
insert into authors (author) values ('Найтов Комбат');
insert into authors (author) values ('Наст Алексей');
insert into authors (author) values ('Наумов Иван');
insert into authors (author) values ('Нгози Адичи Чимаманда');
insert into authors (author) values ('Невестина Ксюра');
insert into authors (author) values ('Некрасов Александр');
insert into authors (author) values ('Некрасова Евгения');
insert into authors (author) values ('Несс Патрик');
insert into authors (author) values ('Нестеров Михаил');
insert into authors (author) values ('Нестерова Наталья');
insert into authors (author) values ('Нигматулина Галина');
insert into authors (author) values ('Ниеми Микаель');
insert into authors (author) values ('Никитин Юрий');
insert into authors (author) values ('Никитина Анастасия');
insert into authors (author) values ('Николаев Михаил');
insert into authors (author) values ('Новожилов Денис');
insert into authors (author) values ('Ной Харари Юваль');
insert into authors (author) values ('Нони Линетт');
insert into authors (author) values ('Норкросс Джон');
insert into authors (author) values ('Норрис Шана');
insert into authors (author) values ('Нун Джефф');
insert into authors (author) values ('Нурисламова Альбина');
insert into authors (author) values ('Нуртазин Сергей');
insert into authors (author) values ('Ньюмейер Марти');
insert into authors (author) values ('Нэвилл Адам');
insert into authors (author) values ('О Коннор Фланнери');
insert into authors (author) values ('О Коннор Ричард');
insert into authors (author) values ('Обрист Ханс Ульрих');
insert into authors (author) values ('Обух Арина');
insert into authors (author) values ('Обухова Елена');
insert into authors (author) values ('Оганесян Мгер');
insert into authors (author) values ('Огаст Джон');
insert into authors (author) values ('Огилви Дэвид');
insert into authors (author) values ('Огинская Купава');
insert into authors (author) values ('Оден Скотт');
insert into authors (author) values ('Озолс Тори');
insert into authors (author) values ('Окан Аланна');
insert into authors (author) values ('Окишева Вера');
insert into authors (author) values ('Оксье Джонатан');
insert into authors (author) values ('Оливер Лорен');
insert into authors (author) values ('Оливсон Милена');
insert into authors (author) values ('Олие Ольга');
insert into authors (author) values ('Оллнатт Люк');
insert into authors (author) values ('Олсон Лейни');
insert into authors (author) values ('Омер Майк');
insert into authors (author) values ('Ондатже Майкл');
insert into authors (author) values ('Онсу Ким');
insert into authors (author) values ('Орвиг Сара');
insert into authors (author) values ('Оренстейн Ханна');
insert into authors (author) values ('Орлов Алекс');
insert into authors (author) values ('Орлова Вероника');
insert into authors (author) values ('Орлова Тальяна');
insert into authors (author) values ('Орловский Гай Юлий');
insert into authors (author) values ('Оруэлл Джордж');
insert into authors (author) values ('Осадчук Алексей');
insert into authors (author) values ('Осипов Максим');
insert into authors (author) values ('Оскар Пфистер');
insert into authors (author) values ('Осман София');
insert into authors (author) values ('Останин Виталий');
insert into authors (author) values ('Остер Пол');
insert into authors (author) values ('Остин Джейн');
insert into authors (author) values ('Остоу Микол');
insert into authors (author) values ('Островская Екатерина');
insert into authors (author) values ('Островский Аркадий');
insert into authors (author) values ('Оуэн Маргарет');
insert into authors (author) values ('Охлобыстин Иван');
insert into authors (author) values ('Оченков Иван');
insert into authors (author) values ('Павлищева Наталья');
insert into authors (author) values ('Пандазопулос Изабель');
insert into authors (author) values ('Панов Вадим');
insert into authors (author) values ('Пантелей');
insert into authors (author) values ('Панфилов Василий');
insert into authors (author) values ('Паолини Кристофер');
insert into authors (author) values ('Парк Джессика');
insert into authors (author) values ('Парр Мария');
insert into authors (author) values ('Пауэрс Тим');
insert into authors (author) values ('Пашнина Ольга');
insert into authors (author) values ('Пейвер Мишель');
insert into authors (author) values ('Пейдж Сабрина');
insert into authors (author) values ('Пейчева Анна');
insert into authors (author) values ('Пекара Яцек');
insert into authors (author) values ('Пелевин Виктор');
insert into authors (author) values ('Пенн Марк');
insert into authors (author) values ('Пенни Луиз');
insert into authors (author) values ('Пенни Луиза');
insert into authors (author) values ('Первушина Елена');
insert into authors (author) values ('Перель Эстер');
insert into authors (author) values ('Перепечина Яна');
insert into authors (author) values ('Перес Кристина');
insert into authors (author) values ('Перетти Паола');
insert into authors (author) values ('Перплис Бернд');
insert into authors (author) values ('Перрен Валери');
insert into authors (author) values ('Перри Амброуз');
insert into authors (author) values ('Перри Энн');
insert into authors (author) values ('Перумов Ник');
insert into authors (author) values ('Першанин Владимир');
insert into authors (author) values ('Пессл Мариша');
insert into authors (author) values ('Петерсен Орсон');
insert into authors (author) values ('Петровичева Лариса');
insert into authors (author) values ('Петросян Мариам');
insert into authors (author) values ('Петручо Стефан');
insert into authors (author) values ('Петрушевская Людмила');
insert into authors (author) values ('Пехов Алексей');
insert into authors (author) values ('Пиблз Франсишь Ди Понтиш');
insert into authors (author) values ('Пиколт Джоди Линн');
insert into authors (author) values ('Пиллэй Шрини');
insert into authors (author) values ('Пилчер Розамунда');
insert into authors (author) values ('Пинборо Сара');
insert into authors (author) values ('Пирс Блейк');
insert into authors (author) values ('Пирс Томпсон Сьюзан');
insert into authors (author) values ('Пирсон Эллисон');
insert into authors (author) values ('Плас Франсуа');
insert into authors (author) values ('Платова Виктория');
insert into authors (author) values ('Платунова Анна');
insert into authors (author) values ('Плетнёв Александр');
insert into authors (author) values ('Поволоцкий Александр');
insert into authors (author) values ('Поляков Влад');
insert into authors (author) values ('Поляков Юрий');
insert into authors (author) values ('Полякова Татьяна');
insert into authors (author) values ('Полянская Алла');
insert into authors (author) values ('Полянская Катерина');
insert into authors (author) values ('Помозов Артём');
insert into authors (author) values ('Пономарёв Александр');
insert into authors (author) values ('Пономарева Татьяна');
insert into authors (author) values ('Попандопуло Анастасия');
insert into authors (author) values ('Попова Надежда');
insert into authors (author) values ('Портер Элинор');
insert into authors (author) values ('Портнягин Дмитрий');
insert into authors (author) values ('Поселягин Владимир');
insert into authors (author) values ('Поспешная Юлия');
insert into authors (author) values ('Пратчетт Терри');
insert into authors (author) values ('Прах Вячеслав');
insert into authors (author) values ('Престон Дуглас');
insert into authors (author) values ('Престон Ив');
insert into authors (author) values ('Престон Наташа');
insert into authors (author) values ('Прилепин Захар');
insert into authors (author) values ('Прозоров Александр');
insert into authors (author) values ('Прокофьев Андрей');
insert into authors (author) values ('Протасов Сергей');
insert into authors (author) values ('Прусенко Владислав');
insert into authors (author) values ('Пулман Филип');
insert into authors (author) values ('Пушкин Александр');
insert into authors (author) values ('Пэган Камилла');
insert into authors (author) values ('Пэдрейра Дэвид');
insert into authors (author) values ('Пэмми Тара');
insert into authors (author) values ('Р.Так Джеймс');
insert into authors (author) values ('Радов Егор');
insert into authors (author) values ('Рай Альмира');
insert into authors (author) values ('Райан Риз');
insert into authors (author) values ('Райдер Кэтрин');
insert into authors (author) values ('Райдер Уиндхэм');
insert into authors (author) values ('Райли Алекса');
insert into authors (author) values ('Раймс Шонда');
insert into authors (author) values ('Райнер Сара');
insert into authors (author) values ('Райт Бетти Рен');
insert into authors (author) values ('Райх Брендан');
insert into authors (author) values ('Райяниеми Ханну');
insert into authors (author) values ('Рака Грег');
insert into authors (author) values ('Ранделл Кэтрин');
insert into authors (author) values ('Расселл Крейг');
insert into authors (author) values ('Рауз Алекс');
insert into authors (author) values ('Рауэлл Рейнбоу');
insert into authors (author) values ('Резерфорд Эдвард');
insert into authors (author) values ('Рейд Тейлор Дженкинс');
insert into authors (author) values ('Рейли Кора');
insert into authors (author) values ('Рейнард Сильвейн');
insert into authors (author) values ('Рейнольдс Николас');
insert into authors (author) values ('Ремарк Эрих Мария');
insert into authors (author) values ('Ренг Рональд');
insert into authors (author) values ('Ренсом С. К.');
insert into authors (author) values ('Ригби Эл');
insert into authors (author) values ('Риггз Ренсом');
insert into authors (author) values ('Рид Ребекка');
insert into authors (author) values ('Риддел Крис');
insert into authors (author) values ('Ридкер Эндрю');
insert into authors (author) values ('Риордан Рик');
insert into authors (author) values ('Риттер Уильям');
insert into authors (author) values ('Робертс Алисон');
insert into authors (author) values ('Робертс Вилло Дэвис');
insert into authors (author) values ('Робертс Грегори Дэвид');
insert into authors (author) values ('Робертс Нора');
insert into authors (author) values ('Робинсон Кен');
insert into authors (author) values ('Робинсон Ким Стэнли');
insert into authors (author) values ('Роджерсон Маргарет');
insert into authors (author) values ('Розофф Мег');
insert into authors (author) values ('Рой Олег');
insert into authors (author) values ('Ройтер Бьярне');
insert into authors (author) values ('Рок Джоанна');
insert into authors (author) values ('Романов Герман');
insert into authors (author) values ('Романова Галина');
insert into authors (author) values ('Романовская Ольга');
insert into authors (author) values ('Рондо Даниэль');
insert into authors (author) values ('Рот Вероника');
insert into authors (author) values ('Роу Дженнифер');
insert into authors (author) values ('Роули Стивен');
insert into authors (author) values ('Роулинг Джоан');
insert into authors (author) values ('Роупер Ричард');
insert into authors (author) values ('Рубанов Андрей');
insert into authors (author) values ('Рубина Дина');
insert into authors (author) values ('Руденко Борис');
insert into authors (author) values ('Рудник Элизабет');
insert into authors (author) values ('Руссо Ричард');
insert into authors (author) values ('Рушди Ахмед Салман');
insert into authors (author) values ('Рыбка Настя');
insert into authors (author) values ('Рэнд Айн');
insert into authors (author) values ('Рябинина Юлия');
insert into authors (author) values ('Рябиченко Антон');
insert into authors (author) values ('Сабаев Тимур');
insert into authors (author) values ('Сабо Магда');
insert into authors (author) values ('Савельева Валерия');
insert into authors (author) values ('Савенко Валентина');
insert into authors (author) values ('Савиано Роберто');
insert into authors (author) values ('Савин Владислав');
insert into authors (author) values ('Савченко Надежда');
insert into authors (author) values ('Сагг Зои');
insert into authors (author) values ('Садловская Мария');
insert into authors (author) values ('Садов Сергей');
insert into authors (author) values ('Сазерленд Кари');
insert into authors (author) values ('Сазерленд Кристал');
insert into authors (author) values ('Сазерленд Тай');
insert into authors (author) values ('Сазерленд Туи Т.');
insert into authors (author) values ('Сазонов Андрей');
insert into authors (author) values ('Саид Аиша');
insert into authors (author) values ('Салиева Александра');
insert into authors (author) values ('Салисбери Мелинда');
insert into authors (author) values ('Салтыков-Щедрин Михаил');
insert into authors (author) values ('Сальваторе Роберт Энтони');
insert into authors (author) values ('Самаров Сергей');
insert into authors (author) values ('Самарский Михаил');
insert into authors (author) values ('Самохин Дмитрий');
insert into authors (author) values ('Сандерсон Брендон');
insert into authors (author) values ('Сапегин Александр');
insert into authors (author) values ('Сапковский Анджей');
insert into authors (author) values ('Сапфир Ясмина');
insert into authors (author) values ('Сарамаго Жозе');
insert into authors (author) values ('Сартр Жан-Поль');
insert into authors (author) values ('Сарычев Анатолий');
insert into authors (author) values ('Сафарли Эльчин');
insert into authors (author) values ('Светерлич Том');
insert into authors (author) values ('Свечин Николай');
insert into authors (author) values ('Свияш Александр');
insert into authors (author) values ('Себаг-Монтефиоре Саймон Джонатан');
insert into authors (author) values ('Сейгер Райли');
insert into authors (author) values ('Сейтимбетов Самат Айдосович');
insert into authors (author) values ('Сейф Мартин Н.');
insert into authors (author) values ('Селиванова Ирина');
insert into authors (author) values ('Селигман Мартин');
insert into authors (author) values ('Семенова Надежда');
insert into authors (author) values ('Сент-Джеймс Симона');
insert into authors (author) values ('Сент-Обин Эдвард');
insert into authors (author) values ('Сервантес Де Мигель');
insert into authors (author) values ('Серганова Татьяна');
insert into authors (author) values ('Серебряков Дмитрий');
insert into authors (author) values ('Серновиц Энди');
insert into authors (author) values ('Серова Марина');
insert into authors (author) values ('Серяков Павел');
insert into authors (author) values ('Сеттерфилд Диана');
insert into authors (author) values ('Сиболд Элис');
insert into authors (author) values ('Сигел Джейсон');
insert into authors (author) values ('Сигитова Екатерина');
insert into authors (author) values ('Сидоров Алексей');
insert into authors (author) values ('Силлов Дмитрий');
insert into authors (author) values ('Симкин Лев');
insert into authors (author) values ('Симон Герман');
insert into authors (author) values ('Симонова Дарья');
insert into authors (author) values ('Сингер Ники');
insert into authors (author) values ('Синицын Андрей');
insert into authors (author) values ('Синклер Шериз');
insert into authors (author) values ('Синсеро Джен');
insert into authors (author) values ('Сиснерос Сандра');
insert into authors (author) values ('Скальци Джон');
insert into authors (author) values ('Скирюк Дмитрий');
insert into authors (author) values ('Скоренко Тим');
insert into authors (author) values ('Скотт Кард Орсон');
insert into authors (author) values ('Слёзкин Юрий');
insert into authors (author) values ('Слюсаренко Сергей');
insert into authors (author) values ('Смекалин Дмитрий');
insert into authors (author) values ('Смелик Эльвира');
insert into authors (author) values ('Смирнов Александр');
insert into authors (author) values ('Смит Али');
insert into authors (author) values ('Смолл Беатрис');
insert into authors (author) values ('Смолл Бертрис');
insert into authors (author) values ('Смородинский Георгий');
insert into authors (author) values ('Сникет Лемони');
insert into authors (author) values ('Соболева Ульяна');
insert into authors (author) values ('Соболь Екатерина');
insert into authors (author) values ('Сойер Бигл Питер');
insert into authors (author) values ('Сойер Роберт Джеймс');
insert into authors (author) values ('Сокол Анна');
insert into authors (author) values ('Сокол Лена');
insert into authors (author) values ('Соловьев Валентин');
insert into authors (author) values ('Солодовиченко Алена');
insert into authors (author) values ('Соротокина Нина');
insert into authors (author) values ('Соул Диана');
insert into authors (author) values ('Спасская Мария');
insert into authors (author) values ('Стайн Роберт Лоуренс');
insert into authors (author) values ('Старицкий Дмитрий');
insert into authors (author) values ('Старк Кристина');
insert into authors (author) values ('Старноне Доменико');
insert into authors (author) values ('Старобинец Анна');
insert into authors (author) values ('Стейси Линда');
insert into authors (author) values ('Стейтен Джозеф');
insert into authors (author) values ('Стен Камилла');
insert into authors (author) values ('Степанов Николай');
insert into authors (author) values ('Степанова Татьяна');
insert into authors (author) values ('Стерн Робин');
insert into authors (author) values ('Стеффан Виндж Вернор');
insert into authors (author) values ('Стешин Дмитрий');
insert into authors (author) values ('Стивенсон Нил');
insert into authors (author) values ('Стил Даниэла');
insert into authors (author) values ('Стил Даяна');
insert into authors (author) values ('Стовер Мэтью');
insert into authors (author) values ('Стогов Илья');
insert into authors (author) values ('Стоун Тамара Айленд');
insert into authors (author) values ('Страут Элизабет');
insert into authors (author) values ('Стрелеки Джон');
insert into authors (author) values ('Стрельникова Кира');
insert into authors (author) values ('Стрит Карен Ли');
insert into authors (author) values ('Стругацкие Братья');
insert into authors (author) values ('Стюарт Колин');
insert into authors (author) values ('Стюарт Мэри');
insert into authors (author) values ('Стюарт Пол');
insert into authors (author) values ('Сувада Эмили');
insert into authors (author) values ('Судакова Алена');
insert into authors (author) values ('Суржевская Марина');
insert into authors (author) values ('Сурикова Марьяна');
insert into authors (author) values ('Сухинин Владимир');
insert into authors (author) values ('Сухов Евгений');
insert into authors (author) values ('Сухоницкий Арсений');
insert into authors (author) values ('Сэ Слава');
insert into authors (author) values ('Сэлинджер Джером Дейвид');
insert into authors (author) values ('Тайлер Энн');
insert into authors (author) values ('Таками Косюн');
insert into authors (author) values ('Таланов Дмитрий');
insert into authors (author) values ('Тамоников Александр');
insert into authors (author) values ('Танари Таша');
insert into authors (author) values ('Тарабан Олег');
insert into authors (author) values ('Тарарев Александр');
insert into authors (author) values ('Тармашев Сергей');
insert into authors (author) values ('Тартт Донна');
insert into authors (author) values ('Таругин Олег');
insert into authors (author) values ('Таршис Лорен');
insert into authors (author) values ('Тахир Саба');
insert into authors (author) values ('Твен Марк');
insert into authors (author) values ('Тебнева Елена');
insert into authors (author) values ('Тейлор Лэйни');
insert into authors (author) values ('Тенн Уильям');
insert into authors (author) values ('Терр Алль');
insert into authors (author) values ('Террилл Кристин');
insert into authors (author) values ('Тиджан');
insert into authors (author) values ('Тилье Франк');
insert into authors (author) values ('Тимошенко Наталья');
insert into authors (author) values ('Тинкер Ребекка');
insert into authors (author) values ('Тиньков Олег');
insert into authors (author) values ('Ткачев Андрей');
insert into authors (author) values ('Тодд Анна');
insert into authors (author) values ('Токарчук Ольга');
insert into authors (author) values ('Толонен Туутикки');
insert into authors (author) values ('Толстая Татьяна');
insert into authors (author) values ('Торвальд Юрген');
insert into authors (author) values ('Торджуссен Мэри');
insert into authors (author) values ('Торн Салли');
insert into authors (author) values ('Тосс Анатолий');
insert into authors (author) values ('Точинов Виктор');
insert into authors (author) values ('Трауб Маша');
insert into authors (author) values ('Траут Джек');
insert into authors (author) values ('Треймо Сесилие');
insert into authors (author) values ('Трейси Брайан');
insert into authors (author) values ('Триджиани Адриана');
insert into authors (author) values ('Троепольский Гавриил');
insert into authors (author) values ('Тронина Татьяна');
insert into authors (author) values ('Трускиновская Далия');
insert into authors (author) values ('Тсокос Михаэль');
insert into authors (author) values ('Тур Тереза');
insert into authors (author) values ('Тюрин Виктор');
insert into authors (author) values ('Уайт Алекс');
insert into authors (author) values ('Уайт Карен');
insert into authors (author) values ('Уайт Кирстен');
insert into authors (author) values ('Уайт Лорет Энн');
insert into authors (author) values ('Уайтхед Колсон');
insert into authors (author) values ('Уатт Эрин');
insert into authors (author) values ('Углицкая Алина');
insert into authors (author) values ('Уивер Эшли');
insert into authors (author) values ('Уигналл Кевин');
insert into authors (author) values ('Уилсон Валери Плейм');
insert into authors (author) values ('Уильямс Тэд');
insert into authors (author) values ('Уинман Сара');
insert into authors (author) values ('Уинн Джонс Диана');
insert into authors (author) values ('Уинтерсон Джанет');
insert into authors (author) values ('Уленгов Юрий');
insert into authors (author) values ('Улицкая Людмила');
insert into authors (author) values ('Ульсон Кристина');
insert into authors (author) values ('Уокер Карен');
insert into authors (author) values ('Уокер Уэнди');
insert into authors (author) values ('Уокер Элис');
insert into authors (author) values ('Уолк Лорен');
insert into authors (author) values ('Уолкер Мэттью');
insert into authors (author) values ('Уоллес Дэвид Фостер');
insert into authors (author) values ('Уолтерс А.Мередит');
insert into authors (author) values ('Уолтерс Виктория');
insert into authors (author) values ('Уорд Пенелопа');
insert into authors (author) values ('Уотсон Джо');
insert into authors (author) values ('Уотсон Кристи');
insert into authors (author) values ('Успенская Ирина');
insert into authors (author) values ('Устинова Татьяна');
insert into authors (author) values ('Ушкова Светлана');
insert into authors (author) values ('Уэбб Дебра');
insert into authors (author) values ('Уэбстер К.');
insert into authors (author) values ('Уэйр Рут');
insert into authors (author) values ('Уэйс Маргарет');
insert into authors (author) values ('Уэкс Руби');
insert into authors (author) values ('Уэллс Марта');
insert into authors (author) values ('Уэлш Ирвин');
insert into authors (author) values ('Уэльбек Мишель');
insert into authors (author) values ('Уэст Кейси');
insert into authors (author) values ('Фавильи Елена');
insert into authors (author) values ('Фархин Мирза Фатима');
insert into authors (author) values ('Фаулз Джон');
insert into authors (author) values ('Федотов Алексей');
insert into authors (author) values ('Феллоуз Джессика');
insert into authors (author) values ('Фергюсон Ниал');
insert into authors (author) values ('Ферранте Элена');
insert into authors (author) values ('Феррацци Кейт');
insert into authors (author) values ('Филагрина Анна');
insert into authors (author) values ('Филимонов Сергий');
insert into authors (author) values ('Филин Яна');
insert into authors (author) values ('Филипенко Саша');
insert into authors (author) values ('Фини Элис');
insert into authors (author) values ('Финкель Майкл');
insert into authors (author) values ('Фирсов Алексей');
insert into authors (author) values ('Фишер Кэтрин');
insert into authors (author) values ('Фламмер Виктор');
insert into authors (author) values ('Фландерс Кейт');
insert into authors (author) values ('Флат Екатерина');
insert into authors (author) values ('Флетчер Сьюзан');
insert into authors (author) values ('Флинн Гиллиан');
insert into authors (author) values ('Флит Кэтрин');
insert into authors (author) values ('Флореску Каталин Дориан');
insert into authors (author) values ('Флэгг Фэнни');
insert into authors (author) values ('Фолкс Себастьян');
insert into authors (author) values ('Фонвизин Денис');
insert into authors (author) values ('Форман Гейл');
insert into authors (author) values ('Фортин Сью');
insert into authors (author) values ('Фрай Макс');
insert into authors (author) values ('Фрай Стивен');
insert into authors (author) values ('Франзен Джонатан');
insert into authors (author) values ('Франк Элла');
insert into authors (author) values ('Франц Анастасия');
insert into authors (author) values ('Фрейм Соня');
insert into authors (author) values ('Фромм Эрих');
insert into authors (author) values ('Функе Корнелия');
insert into authors (author) values ('Ффорде Джаспер');
insert into authors (author) values ('Хаас Ричард');
insert into authors (author) values ('Хайнлайн Роберт');
insert into authors (author) values ('Хаксли Олдос');
insert into authors (author) values ('Халецкий Антон');
insert into authors (author) values ('Халлинан Джозеф');
insert into authors (author) values ('Хама Ларри');
insert into authors (author) values ('Хан Дженни');
insert into authors (author) values ('Хан Ксения');
insert into authors (author) values ('Ханна Софи');
insert into authors (author) values ('Хансен Мортен');
insert into authors (author) values ('Хант Диана');
insert into authors (author) values ('Хантер Стивен');
insert into authors (author) values ('Хардинг Фрэнсис');
insert into authors (author) values ('Хари Йоханн');
insert into authors (author) values ('Харкнесс Дебора');
insert into authors (author) values ('Хармон Эми');
insert into authors (author) values ('Харников Александр');
insert into authors (author) values ('Харрис Джоанн');
insert into authors (author) values ('Харрис Роберт');
insert into authors (author) values ('Харрис Томас');
insert into authors (author) values ('Харрисон Лизи');
insert into authors (author) values ('Харт Джон');
insert into authors (author) values ('Харт Уна');
insert into authors (author) values ('Хартман Рейчел');
insert into authors (author) values ('Хартцлер Аарон');
insert into authors (author) values ('Хаус Льюис');
insert into authors (author) values ('Хаффингтон Арианна');
insert into authors (author) values ('Хейер Джорджетт');
insert into authors (author) values ('Хейл Йерун ван');
insert into authors (author) values ('Хейнрикс Джей');
insert into authors (author) values ('Хемингуэй Эрнест Миллер');
insert into authors (author) values ('Хеннинг Сара');
insert into authors (author) values ('Херберт Фрэнк');
insert into authors (author) values ('Херманс Виллем Фредерик');
insert into authors (author) values ('Хесс Аннетте');
insert into authors (author) values ('Хиберлин Джулия');
insert into authors (author) values ('Хиггинс Кларк Мэри');
insert into authors (author) values ('Хилл Джо');
insert into authors (author) values ('Химмельман Питер');
insert into authors (author) values ('Хирачев Гулла');
insert into authors (author) values ('Хитрикова Нина');
insert into authors (author) values ('Хобб Робин');
insert into authors (author) values ('Ховард Кэт');
insert into authors (author) values ('Ходаницкий Евгений');
insert into authors (author) values ('Ходж Брайан');
insert into authors (author) values ('Хокинс Пола');
insert into authors (author) values ('Хокинс Рейчел');
insert into authors (author) values ('Хокс Джон');
insert into authors (author) values ('Холл Патрик Дж.');
insert into authors (author) values ('Холлс Стейси');
insert into authors (author) values ('Холт Кристофер');
insert into authors (author) values ('Хоссейни Халед');
insert into authors (author) values ('Хохлатов Алексей');
insert into authors (author) values ('Храмов Виталий');
insert into authors (author) values ('Хувер Стеф');
insert into authors (author) values ('Хьюлетт Сильвия Энн');
insert into authors (author) values ('Хэ Джоан');
insert into authors (author) values ('Хэдли Чейз Джеймс');
insert into authors (author) values ('Хэлворсон Хайди Грант');
insert into authors (author) values ('Хэнд Синтия');
insert into authors (author) values ('Хэнд Элизабет');
insert into authors (author) values ('Цимерман Джессика');
insert into authors (author) values ('Цинкк Валия');
insert into authors (author) values ('Цыпкин Александр');
insert into authors (author) values ('Цюфань Чэнь');
insert into authors (author) values ('Чайковский Адриан');
insert into authors (author) values ('Чайлд Линкольн');
insert into authors (author) values ('Чайлд Морин');
insert into authors (author) values ('Чайма Синда Уильямс');
insert into authors (author) values ('Чайнани Соман');
insert into authors (author) values ('Чакраборти Шеннон А.');
insert into authors (author) values ('Чарлтон Блейк');
insert into authors (author) values ('Чбоски Стивен');
insert into authors (author) values ('Чевкина Екатерина');
insert into authors (author) values ('Чейлефф Айра');
insert into authors (author) values ('Черевков Владимир');
insert into authors (author) values ('Чередий Галина');
insert into authors (author) values ('Черная Людмила');
insert into authors (author) values ('Чернованова Валерия');
insert into authors (author) values ('Черчень Александра');
insert into authors (author) values ('Чиж Антон');
insert into authors (author) values ('Чижов Евгений');
insert into authors (author) values ('Чижова Елена');
insert into authors (author) values ('Чижъ Антон');
insert into authors (author) values ('Чиркова Вера');
insert into authors (author) values ('Чокши Рошани');
insert into authors (author) values ('Шабанов Сергей');
insert into authors (author) values ('Шайсултанов Ильяс');
insert into authors (author) values ('Шалыгин Вячеслав');
insert into authors (author) values ('Шама Саймон');
insert into authors (author) values ('Шаман Иван');
insert into authors (author) values ('Шапочкин Александр');
insert into authors (author) values ('Шарапов Валерий');
insert into authors (author) values ('Шарапов Кирилл');
insert into authors (author) values ('Шаргородский Григорий');
insert into authors (author) values ('Шареноу Роберт');
insert into authors (author) values ('Шарипов Никита');
insert into authors (author) values ('Шахматова Татьяна');
insert into authors (author) values ('Шахов Максим');
insert into authors (author) values ('Шваб Виктория');
insert into authors (author) values ('Швалль-Вейганд Эсме');
insert into authors (author) values ('Шеверс Дж. Э.');
insert into authors (author) values ('Шевченко Ирина');
insert into authors (author) values ('Шейл Рута');
insert into authors (author) values ('Шейн Эдгар');
insert into authors (author) values ('Шейнов Виктор');
insert into authors (author) values ('Шейфер Дэвид');
insert into authors (author) values ('Шелег Дмитрий');
insert into authors (author) values ('Шелег Игорь');
insert into authors (author) values ('Шенгальц Игорь');
insert into authors (author) values ('Шервуд Бен');
insert into authors (author) values ('Шерр Анастасия');
insert into authors (author) values ('Шерстобитова Ольга');
insert into authors (author) values ('Шилд Кэт');
insert into authors (author) values ('Шифрин Михаил');
insert into authors (author) values ('Шифф Стейси');
insert into authors (author) values ('Шкутова Юлия');
insert into authors (author) values ('Шляхов Андрей');
insert into authors (author) values ('Шмайссер Франк');
insert into authors (author) values ('Шмелев Вадим');
insert into authors (author) values ('Шойнеманн Фрауке');
insert into authors (author) values ('Шолохов Михаил');
insert into authors (author) values ('Шолохова Елена');
insert into authors (author) values ('Шольте Астрид');
insert into authors (author) values ('Шустерман Нил');
insert into authors (author) values ('Шушеньков Александр');
insert into authors (author) values ('Щеглова Ирина');
insert into authors (author) values ('Щепетнов Евгений');
insert into authors (author) values ('Щерба Наталья');
insert into authors (author) values ('Щукин Михаил');
insert into authors (author) values ('Эванс Хэрриет');
insert into authors (author) values ('Эвенсон Брайан');
insert into authors (author) values ('Эгер Эдит');
insert into authors (author) values ('Эдблад Патрик');
insert into authors (author) values ('Эдвардссон Маттиас');
insert into authors (author) values ('Элизабет МакНиллбет');
insert into authors (author) values ('Элиот Джордж');
insert into authors (author) values ('Эллис Джой');
insert into authors (author) values ('Элтон Бен');
insert into authors (author) values ('Эльба Ирина');
insert into authors (author) values ('Эльденберт Марина');
insert into authors (author) values ('Эльсберг Марк');
insert into authors (author) values ('Эрикссон Каролина');
insert into authors (author) values ('Эрикссон Мартин');
insert into authors (author) values ('Эрлбаум Дженис');
insert into authors (author) values ('Эрлинг Ирис');
insert into authors (author) values ('Эрлих Генрих');
insert into authors (author) values ('Эшбах Андреас');
insert into authors (author) values ('Эштон Броди');
insert into authors (author) values ('Юнгстедт Мари');
insert into authors (author) values ('Яковлева Алена');
insert into authors (author) values ('Якушевская Влада');
insert into authors (author) values ('Янг Саманта');
insert into authors (author) values ('Янг Эдриенн');
insert into authors (author) values ('Янук Елена');
insert into authors (author) values ('Янч Джон');
insert into authors (author) values ('Ярыгин Николай');
insert into authors (author) values ('Ясинская Марина');
insert into authors (author) values ('Ясинский Анджей');
insert into authors (author) values ('Яхина Гузель');